package com.geekbrains.model;

public enum Operation {
    DELETE_FILE,
    SERVER_LIST_MESSAGE,
    LOCAL_LIST_MESSAGE,
    FILE_REQUEST_TO_LOCAL,
    FILE_REQUEST_TO_SERVER,
    FILE_MESSAGE_TO_LOCAL,
    FILE_MESSAGE_TO_SERVER,
    RENAME_FILE,
    SYSTEM_MESSAGE,
    REGISTRATION,
    LOGIN,
    LOGIN_OK,
    EXIT_REQUEST,
    OPEN_FILE,
    CREATE_FOLDER
}
